---
name: Data Product - prison-example - Test

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/data-product-prison-example-test.yaml
      - data-products/example_prison_data_product/**
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-products/example_prison_data_product
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.10]
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: pytest
