---
name: Data Product - prison-example - Upload

on:
  push:
    branches:
      - main
    paths:
      - data-products/example_prison_data_product/**
      - .github/workflows/data-product-prison-example-upload.yaml

jobs:
  test:
    uses: ./.github/workflows/data-product-prison-example-test.yaml

  upload:
    name: Zip and upload
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write # This is required for requesting the JWT
    defaults:
      run:
        working-directory: data-products/example_prison_data_product
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5.0
      - name: Set up Python 3.10.10
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: 3.10.10
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Zip data product
        run: python package_data_product.py
      - name: OIDC Authentication
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::013433889002:role/data-platform-labs-github-role
          aws-region: eu-west-2
          role-duration-seconds: 3600
          role-session-name: githubactionsiamsession
      - name: Push to s3
        env:
          BUCKET_NAME: data-platform-products-development20230412155038755500000001
        run: |
          aws s3 sync . s3://$BUCKET_NAME/code_zips/example_prison_data_product/ \
            --exclude '*' --include 'data_product_example_prison_data_product.zip'
