---
name: Data Product - example_2 - Test

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/data-product-example-2-test.yaml
      - data-products/example_2/**
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-products/example_2
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.10]
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          pip install --requirement requirements.txt

      - name: Run tests with pytest
        run: |
          pytest tests/ -vv;
