---
name: POC - zip and upload _example_2

on:
  push:
    branches:
      - main
    paths:
      - 'data-products/**'
      - '.github/workflows/zip-data-products.yml'
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'data-products/**'
      - '.github/workflows/zip-data-products.yml'

jobs:
  preview:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    defaults:
      run:
        working-directory: data-products
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.10]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: pip install -r _example_2/requirements.txt
      - name: Zip data product
        run: python package_data_product.py
      - name: OIDC Authentication
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::013433889002:role/data-platform-labs-github-actions
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: githubactionsiamsession
      - name: Push to s3
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.CICD_MEMBER_USER_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.CICD_MEMBER_USER_KEY }}
#           AWS_DEFAULT_REGION: eu-west-2
#           BUCKET_NAME: data-platform-products-sandbox20230328133227039700000001
        run: |
          aws s3 sync . s3://$BUCKET_NAME/_example_2/code/extraction_timestamp=$(date +%Y%m%d%H%M%S)/ \
            --exclude '*' --include 'data_product__example_2.zip'
